#!/bin/bash
export GOPATH=$(pwd)
go get -v golang.org/x/crypto/bcrypt
go get -v github.com/mattn/go-sqlite3
go get -v github.com/jinzhu/gorm
go get -v github.com/gorilla/mux
go get -v github.com/dgrijalva/jwt-go
go get -v github.com/joho/godotenv
